### ISSUE TITLE
[BUG] Lazymc cannot start recent versions of forge

### ISSUE THREAD

**Issue by wolfeservices** [Okazakee/mcserver-lazymc-docker#24]
## Description
Recent versions of forge have switched to using java headful library loading rather than jar files.
The container bulldozes the startup command line rendering users unable to change the default command to: 
java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.2-40.2.9/unix_args.txt nogui
which is how forge expects to be invoked for MC Versions higher than 1.17.1

## Steps to Reproduce

sudo docker run -p 25565:25565 -e SERVER_PROVIDER=forge -e MC_VERSION=1.18.2 -e SERVER_BUILD=1.18.2-40.2.9  okazakee/mcserver-lazymc-docker

## Behavior
The container tries to start the server, but it fails due to no headful library support

Forge Logs:
[forge-1.18.2-1.18.2-40.2.9.jar.log](https://github.com/Okazakee/mcserver-lazymc-docker/files/14135275/forge-1.18.2-1.18.2-40.2.9.jar.log)

## Your Environment
- Docker okazakee/mcserver-lazymc-docker:latest

**Comment by wolfeservices** [comment]
I have corrected the issue and created a pull request.

**Comment by Okazakee** [comment]
My man you are awesome, thank you very much, i will merge this and hope image building goes well.
