### ISSUE TITLE
Config "lazymc.toml" is not updated on the first startup

### ISSUE THREAD

**Issue by JFingerle** [Okazakee/mcserver-lazymc-docker#9]
On the very first startup of the container (empty volume dir) the "lazymc.toml" is generated but not updated/modified afterwards.

This happens because the logic in "mcserver.sh" to modify the "lazymc.toml" file is only executed if the "lazymc.toml" file already exists.

Workaround: Restart the container. On the second startup "lazymc.toml" will be modified correctly.

Proposed fix: Move the lines after line 212 ("Add new values to lazymc.toml") out of the else-block so they will be always executed when the script runs.

**Comment by Okazakee** [comment]
There are major changes in the next release, it was already fixed in staging, I'm gonna push a hotfix for that in master. Thanks!

**Comment by Okazakee** [comment]
Please let me know if it is fixed, I cannot test for now :\

**Comment by JFingerle** [comment]
> Please let me know if it is fixed, I cannot test for now :\

Thank you, but unfortunately now "lazymc.toml" is not being generated anymore :( It happens because the command to generate the file is missing now ("./lazymc config generate").

**Comment by Okazakee** [comment]
> > Please let me know if it is fixed, I cannot test for now :\
> 
> Thank you, but unfortunately now "lazymc.toml" is not being generated anymore :( It happens because the command to generate the file is missing now ("./lazymc config generate").

OMG I'M SO SORRY, I missed a copy paste, new fix incoming!

**Comment by JFingerle** [comment]
No problem :) Thank you so much for creating this docker image. It is running great and is exactly what I've been looking for.

Issue has been fixed with [4a30339](https://github.com/Okazakee/mcserver-lazymc-docker/commit/4a30339e75bb43c5976a61b4f574890f5446bcde)
